Models/ErrorViewModel.cs
namespace OneTimePasswordManager.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/ValidPassword.cs
using System.ComponentModel.DataAnnotations;

namespace OneTimePasswordManager.Models
{
    public class ValidPassword
    {
        [Required]
        [RegularExpression("^[0-9]+$")]
        public string UserId { get; set; }

        [Required]
        [StringLength(40)]
        public string Password { get; set; }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OneTimePasswordManager.Data;
using OneTimePasswordManager.Models;
using System.Collections.Concurrent;
using System.Diagnostics;

namespace OneTimePasswordManager.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;


        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/PasswordController.cs
using Microsoft.AspNetCore.Mvc;
using OneTimePasswordManager.Data;
using OneTimePasswordManager.Models;

namespace OneTimePasswordManager.Controllers
{
    public class PasswordController : Controller
    {
        private readonly IAppDbContext _context;

        public PasswordController(IAppDbContext context)
        {
            _context = context;
        }

        [HttpPost]
        public IActionResult Submit(IFormCollection form)
        {
            // Access the submitted form data
            string? userId = form["userId"];
            string? date = form["date"];
            string? time = form["time"];
            bool currentDateTime = form["currentDateTime"] == "on";

            Console.WriteLine(userId + " " + date + " " + time + " " + currentDateTime);

            // If any of the form data is missing, return an error.
            if (userId == null || date == null || time == null)
            {
                return Json(new
                {
                    success = false,
                    error = "Unexpected Error!"
                });
            }

            // A few things to note here:
            // 1. The password is generated using the SHA1 algorithm.
            // 2. The password is generated using the user ID, date, and time.
            // 3. The password "randomly" uses upper and lower case letters.
            string password = Utilities.PasswordUtility.Generate(userId + " " + date + " " + time);

            var validPassword = _context.Passwords.FirstOrDefault(vp => vp.UserId == userId);
            if (validPassword == null)
            {
                _context.Passwords.Add(new ValidPassword { UserId = userId, Password = password });
                if (_context.SaveChanges() > 0)
                {
                    return Json(new
                    {
                        success = true,
                        userId,
                        password
                    });
                }
            }

            return Json(new
            {
                success = false,
                error = "Unexpected Error!"
            });
        }

        [HttpPost]
        public IActionResult Reset(IFormCollection form)
        {
            if (form == null)
            {
                return Json(new
                {
                    success = true,
                });
            }

            string? userId = form["userId"];

            var validPassword = _context.Passwords.FirstOrDefault(u => u.UserId == userId);
            if (validPassword != null)
            {
                _context.Passwords.Remove(validPassword);
                if (_context.SaveChanges() > 0)
                {
                    return Json(new
                    {
                        success = true
                    });
                }
            }

            return Json(new
            {
                success = false,
                error = "Unexpected Error!"
            });
        }

        [HttpPost]
        public IActionResult Check(IFormCollection form)
        {
            string? password = form["passwordCheck"];

            if (password == null)
            {
                return Json(new
                {
                    success = false,
                    error = "Unexpected Error!"
                });
            }

            var validPassword = _context.Passwords.FirstOrDefault(u => u.Password == password);
            if (validPassword != null)
            {
                return Json(new
                {
                    success = true,
                    found = true
                });
            }

            return Json(new
            {
                success = true,
                found = false
            });
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<form id="userForm" action="@Url.Action("Submit", "Password")" method="post"> 
    <label for="userId">User ID:</label>
    <input type="text" id="userId" name="userId" pattern="\d*" title="Please enter only digits" required>
    <br><br>

    <label for="date">Date:</label>
    <input type="date" id="date" name="date" required>
    <br><br>

    <label for="time">Time:</label>
    <input type="time" id="time" name="time" required>
    <br><br>

    <input type="checkbox" id="currentDateTime" name="currentDateTime" onchange="toggleDateTimeFields()">
    <label for="currentDateTime">Check this if you want to take the current DateTime</label>
    <br><br>

    <input type="submit" value="Submit">
</form>

<div id="resultDiv" style="display:none;">
    <label id="resultLabel">Your password is:</label>
    <div id="countdownDiv">
        <progress id="countdownBar" value="0" max="30"></progress>
        <label id="countdownValue">Countdown Finished!</label>
    </div>
</div>


<br><br>

<form id="checkForm" action="@Url.Action("Check", "Password")" method="post">
    <label for="passwordCheck">Password:</label>
    <input type="text" id="passwordCheck" name="passwordCheck" required>
    <br><br>

    <input type="submit" value="Submit">
    <br><br>

    <label id="checkLabel"></label>
</form>



<script>
    var userId = null;

    function toggleDateTimeFields() {
        var checkbox = document.getElementById("currentDateTime");
        var dateField = document.getElementById("date");
        var timeField = document.getElementById("time");

        if (checkbox.checked) {
            // .toISOString() returns a string in the format "yyyy-MM-ddTHH:mm:ss.sssZ"
            var currentDateTime = new Date().toISOString();
            // The first 10 characters are the date in the format "yyyy-MM-dd"
            dateField.value = currentDateTime.slice(0, 10);
            // The next 6 characters are the time in the format "HH:mm"
            timeField.value = currentDateTime.slice(11, 16);
            // The rest of the characters are irrelevant

            dateField.readOnly = true;
            timeField.readOnly = true;
        } else {
            dateField.readOnly = false;
            timeField.readOnly = false;
        }
    }

    document.getElementById("checkForm").addEventListener("submit", function (event) {
        // We need to prevent the default behavior of the form submission
        event.preventDefault(); 

        var form = event.target;
        var data = new FormData(form);
        var checkLabel = document.getElementById("checkLabel");

        var request = new XMLHttpRequest();
        request.open('POST', form.action, true);
        request.onload = function () {
            if (request.status === 200) {
                var response = JSON.parse(request.responseText);
                if (response.found) {
                    checkLabel.innerHTML = "Your password is valid! :)";
				} else {
                    checkLabel.innerHTML = "Your password is invalid! :(";
				}
			} else {
				console.error("Error: " + request.status + " " + request.statusText);
            }
        };
        request.send(data);
    });

    document.getElementById("userForm").addEventListener("submit", function (event) {
		// We need to prevent the default behavior of the form submission
		event.preventDefault(); 

		var form = event.target;
		var data = new FormData(form);
		var resultLabel = document.getElementById("resultLabel");

		var request = new XMLHttpRequest();
		request.open('POST', form.action, true);
		request.onload = function () {
			if (request.status === 200) {
				var response = JSON.parse(request.responseText);
				if (response.success) {
					resultLabel.innerHTML = "Your password is: " + response.password;
					userId = response.userId;
					startCountdown();
				} else {
					console.error("Error: " + response.error);
				}
            } else {
                console.error("Error: " + request.status + " " + request.statusText);
            }
        };
        request.send(data);
    });

    function startCountdown(userId) {
        // A few things to mention here:
        // The countdown is done on the client side.
        // That means that the user can refresh the page and the countdown will start again.
        // However, the password is generated on the server side, so the user will get a new password.
        var seconds = 30;
        var countdownValue = document.getElementById('countdownValue');
        var countdownBar = document.getElementById('countdownBar');

        var resultDiv = document.getElementById("resultDiv");
        var resultLabel = document.getElementById("resultLabel");

        var countdownInterval = setInterval(function() {
            countdownValue.innerHTML = seconds + ' seconds remaining';
            countdownBar.value = seconds;

            if(resultDiv.style.display !== "block") {
				resultDiv.style.display = "block";
			}

            seconds--;
            if (seconds < 0) {
                clearInterval(countdownInterval);
                clearPassword();
                countdownValue.innerHTML = 'Countdown finished';
            }
        }, 1000);
	}

    function clearPassword() {
        var request = new XMLHttpRequest();
        var data = new FormData();
        data.append('userId', userId);
        request.open("POST", '@Url.Action("Reset", "Password")', true);
        request.onload = function () {
            if (request.status === 200) {
                var response = JSON.parse(request.responseText);
                if (response.success) {
                    resultLabel.innerHTML = "Your password is:";
                    resultDiv.style.display = "none";
                } else {
                    console.error("Error: " + response.error);
                }
            }
        };
        request.send(data);
    }

    window.addEventListener('beforeunload', function(event) {
        console.log("Clearing password");
        clearPassword();
    });

</script>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OneTimePasswordManager</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/OneTimePasswordManager.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">OneTimePasswordManager</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - OneTimePasswordManager - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>